baseURL = 'https://itp.nkozak.com/'
languageCode = 'en-us'
title = 'Nikolai Kozak - ITP Blog'
theme = "shibui"

[params]
  author = "Nikolai Kozak"
  email = "nikokozak@gmail.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Shared Minds"
    url = "/tags/shared-minds/"
    weight = 2
  [[menu.main]]
    name = "Understanding Networks"
    url = "/tags/understanding-networks/"
    weight = 3
  [[menu.main]]
    name = "Project Development"
    url = "/tags/project-development/"
    weight = 4
  [[menu.main]]
    name = "Real Estate Finance"
    url = "/tags/real-estate-finance/"
    weight = 5
  [[menu.main]]
    name = "Thesis"
    url = "/tags/thesis/"
    weight = 6
  [[menu.main]]
    name = "Reflections"
    url = "/tags/reflections/"
    weight = 7
  [[menu.main]]
    name = "CS644"
    url = "/tags/cs644/"
    weight = 8c

[markup.goldmark.renderer]
  unsafe = true