baseURL = 'https://itp.nyu.edu/'
languageCode = 'en-us'
title = 'Nikolai Kozak - ITP Blog'
theme = "shibui"

[params]
  author = "Nikolai Kozak"
  email = "nikokozak@gmail.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
