# A name for your workflow
name: Build & Deploy Hugo to Droplet

# This 'on' block tells GitHub WHEN to run the action
on:
  # Run this workflow every time you push to the `main` branch
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# The 'jobs' block defines what the action actually DOES
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Use rsync to sync the 'public' directory to your server
            # The --delete flag removes old files from the server
            rsync -avz --delete ./public/ ${{ secrets.TARGET_DIR }}
