# A name for your workflow
name: Build & Deploy Hugo to Droplet

# This 'on' block tells GitHub WHEN to run the action
on:
  # Run this workflow every time you push to the `main` branch
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# The 'jobs' block defines what the action actually DOES
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          # Add the server's host key to known_hosts to avoid manual confirmation
          ssh-keyscan -H "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts
          
          # Run the rsync command to sync the files
          rsync -avz --delete ./public/ ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:${{ secrets.TARGET_DIR }}
